/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Favorites: typeof import('./src/components/Favorites.vue')['default']
    IntroCard: typeof import('./src/components/IntroCard.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    SkillChart: typeof import('./src/components/SkillChart.vue')['default']
  }
}
